version: '3'

services:
  redis:
    image: 'redis:alpine'
    ports:
      - '6379:6379'
    networks:
      - my-network
  app:
    build: .
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/app
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    networks:
      - my-network

networks:
  my-network: